#define SET_USER_LEVEL 0;

#define GET_USER_LEVEL 1;

#define DELETE_USER_LEVEL 2;

#define SET_FILE_LEVEL 3;

#define GET_FILE_LEVEL 4;

#define DELETE_FILE_LEVEL 5;

#define SET_USER_TO_OTHER_LEVEL 6;

#define GET_USER_TO_OTHER_LEVEL 7;

#define DELETE_USER_TO_OTHER_LEVEL 8;
